version: '3.7'
services:
    application:
        container_name: test_suite_app
        image: richcongress/php:8.0
        volumes:
            - .:/app:rw,cached
            - ~/.composer:/home/application/.composer:cached
